# Generated by Django 5.1.7 on 2025-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
    ]
